### ISSUE TITLE
place order error ? or am i being idiot ?

### ISSUE THREAD

**Issue by sirfrank** [okxapi/python-okx#31]
result = tradeAPI.place_order(
    instId="BCH-USDT-SWAP",
    tdMode="cross",
    side="buy",
    ordType="market",
    # reduceOnly=True,
    sz=1
)
print(result)

throwing error : 

Traceback (most recent call last):
  File "/home/feca/PycharmProjects/OKX/xx_pg_place_order.py", line 20, in <module>
    result = tradeAPI.place_order(
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/okx/Trade.py", line 19, in place_order
    return self._request_with_params(POST, PLACR_ORDER, params)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/okx/client.py", line 46, in _request_with_params
    return self._request(method, request_path, params)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/okx/client.py", line 39, in _request
    response = self.client.post(request_path, data=body, headers=header)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_client.py", line 801, in request
    request = self.build_request(
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_client.py", line 347, in build_request
    headers = self._merge_headers(headers)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_client.py", line 414, in _merge_headers
    merged_headers.update(headers)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_models.py", line 200, in update
    headers = Headers(headers)
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_models.py", line 71, in __init__
    self._list = [
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_models.py", line 75, in <listcomp>
    normalize_header_value(v, encoding),
  File "/home/feca/PycharmProjects/OKX/env_OKX/lib/python3.10/site-packages/httpx/_utils.py", line 54, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'int' object has no attribute 'encode'

**Comment by georgeamine** [comment]
most likely you have initialised tradeAPI with flag set to 0 or 1 (integers)... when the argument needs it as a string. So replace with '0' or '1'.

hope that helps
