### ISSUE TITLE
ws have no auto reconnect,need some example to handle 

### ISSUE THREAD

**Issue by mostcute** [okxapi/python-okx#52]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<WsPublicAsync.consume() done, defined at /root/anaconda3/lib/python3.9/site-packages/okx/websocket/WsPublicAsync.py:22> exception=ConnectionClosedError(None, Close(code=1011, reason='keepalive ping timeout'), None)>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/okx/websocket/WsPublicAsync.py", line 23, in consume
    async for message in self.websocket:
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 497, in __aiter__
    yield await self.recv()
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

**Comment by Tarryhao** [comment]
> In the new websocket method, we don't adopt auto reconnect feature.

so, how to auto reconnect?
